set (
	IRODS_SERVER_CORE_INCLUDE_HEADERS
	${IRODS_SOURCE_DIR}/server/core/include/collection.hpp
	${IRODS_SOURCE_DIR}/server/core/include/dataObjOpr.hpp
	${IRODS_SOURCE_DIR}/server/core/include/fileOpr.hpp
	${IRODS_SOURCE_DIR}/server/core/include/initServer.hpp
	${IRODS_SOURCE_DIR}/server/core/include/irodsReServer.hpp
	${IRODS_SOURCE_DIR}/server/core/include/irodsXmsgServer.hpp
	${IRODS_SOURCE_DIR}/server/core/include/irods_api_calling_functions.hpp
	${IRODS_SOURCE_DIR}/server/core/include/irods_at_scope_exit.hpp
	${IRODS_SOURCE_DIR}/server/core/include/irods_collection_object.hpp
	${IRODS_SOURCE_DIR}/server/core/include/irods_data_object.hpp
	${IRODS_SOURCE_DIR}/server/core/include/irods_database_constants.hpp
	${IRODS_SOURCE_DIR}/server/core/include/irods_database_factory.hpp
	${IRODS_SOURCE_DIR}/server/core/include/irods_database_manager.hpp
	${IRODS_SOURCE_DIR}/server/core/include/irods_database_object.hpp
	${IRODS_SOURCE_DIR}/server/core/include/irods_database_plugin.hpp
	${IRODS_SOURCE_DIR}/server/core/include/irods_database_types.hpp
	${IRODS_SOURCE_DIR}/server/core/include/irods_dynamic_cast.hpp
	${IRODS_SOURCE_DIR}/server/core/include/irods_file_object.hpp
	${IRODS_SOURCE_DIR}/server/core/include/irods_generic_database_object.hpp
	${IRODS_SOURCE_DIR}/server/core/include/irods_get_l1desc.hpp
	${IRODS_SOURCE_DIR}/server/core/include/irods_linked_list_iterator.hpp
	${IRODS_SOURCE_DIR}/server/core/include/irods_mysql_object.hpp
	${IRODS_SOURCE_DIR}/server/core/include/irods_oracle_object.hpp
	${IRODS_SOURCE_DIR}/server/core/include/irods_physical_object.hpp
	${IRODS_SOURCE_DIR}/server/core/include/irods_postgres_object.hpp
	${IRODS_SOURCE_DIR}/server/core/include/irods_resource_backport.hpp
	${IRODS_SOURCE_DIR}/server/core/include/irods_resource_constants.hpp
	${IRODS_SOURCE_DIR}/server/core/include/irods_resource_manager.hpp
	${IRODS_SOURCE_DIR}/server/core/include/irods_resource_plugin.hpp
	${IRODS_SOURCE_DIR}/server/core/include/irods_resource_plugin_impostor.hpp
	${IRODS_SOURCE_DIR}/server/core/include/irods_resource_redirect.hpp
	${IRODS_SOURCE_DIR}/server/core/include/irods_resource_types.hpp
	${IRODS_SOURCE_DIR}/server/core/include/irods_rs_comm_query.hpp
	${IRODS_SOURCE_DIR}/server/core/include/irods_server_api_call.hpp
	${IRODS_SOURCE_DIR}/server/core/include/irods_server_api_table.hpp
	${IRODS_SOURCE_DIR}/server/core/include/irods_server_control_plane.hpp
	${IRODS_SOURCE_DIR}/server/core/include/irods_server_state.hpp
	${IRODS_SOURCE_DIR}/server/core/include/irods_structured_object.hpp
	${IRODS_SOURCE_DIR}/server/core/include/miscServerFunct.hpp
	${IRODS_SOURCE_DIR}/server/core/include/objDesc.hpp
	${IRODS_SOURCE_DIR}/server/core/include/objMetaOpr.hpp
	${IRODS_SOURCE_DIR}/server/core/include/physPath.hpp
	${IRODS_SOURCE_DIR}/server/core/include/procLog.h
	${IRODS_SOURCE_DIR}/server/core/include/resource.hpp
	${IRODS_SOURCE_DIR}/server/core/include/rodsAgent.hpp
	${IRODS_SOURCE_DIR}/server/core/include/rodsConnect.h
	${IRODS_SOURCE_DIR}/server/core/include/rodsServer.hpp
	${IRODS_SOURCE_DIR}/server/core/include/rsApiHandler.hpp
	${IRODS_SOURCE_DIR}/server/core/include/rsGlobalExtern.hpp
	${IRODS_SOURCE_DIR}/server/core/include/rsIcatOpr.hpp
	${IRODS_SOURCE_DIR}/server/core/include/rsLog.hpp
	${IRODS_SOURCE_DIR}/server/core/include/specColl.hpp
	${IRODS_SOURCE_DIR}/server/core/include/xmsgLib.hpp
)
