set (
	IRODS_LIB_CORE_INCLUDE_HEADERS
	${IRODS_SOURCE_DIR}/lib/core/include/apiHandler.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/base64.h
	${IRODS_SOURCE_DIR}/lib/core/include/bunUtil.h
	${IRODS_SOURCE_DIR}/lib/core/include/chksumUtil.h
	${IRODS_SOURCE_DIR}/lib/core/include/connection_pool.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/cpUtil.h
	${IRODS_SOURCE_DIR}/lib/core/include/dstream.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/fsckUtil.h
	${IRODS_SOURCE_DIR}/lib/core/include/getRodsEnv.h
	${IRODS_SOURCE_DIR}/lib/core/include/getUtil.h
	${IRODS_SOURCE_DIR}/lib/core/include/guiProgressCallback.h
	${IRODS_SOURCE_DIR}/lib/core/include/irods_assert.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/irods_auth_constants.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/irods_auth_factory.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/irods_auth_manager.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/irods_auth_object.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/irods_generic_auth_object.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/irods_auth_plugin.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/irods_auth_types.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/irods_buffer_encryption.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/irods_children_parser.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/irods_client_api_table.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/irods_client_server_negotiation.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/irods_configuration_keywords.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/irods_configuration_parser.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/irods_default_paths.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/irods_environment_properties.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/irods_error.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/irods_exception.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/irods_first_class_object.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/irods_get_full_path_for_config_file.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/irods_gsi_object.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/irods_hash.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/irods_hashtable.h
	${IRODS_SOURCE_DIR}/lib/core/include/irods_hierarchy_parser.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/irods_krb_object.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/irods_kvp_string_parser.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/irods_lexical_cast.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/irods_list.h
	${IRODS_SOURCE_DIR}/lib/core/include/irods_load_plugin.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/irods_log.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/irods_lookup_table.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/irods_native_auth_object.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/irods_network_constants.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/irods_network_factory.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/irods_network_manager.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/irods_network_object.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/irods_network_plugin.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/irods_network_types.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/irods_osauth_auth_object.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/irods_pack_table.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/irods_pam_auth_object.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/irods_parse_command_line_options.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/irods_path_recursion.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/irods_pluggable_auth_scheme.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/irods_plugin_base.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/irods_plugin_context.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/irods_plugin_name_generator.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/irods_query.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/irods_random.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/irods_serialization.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/irods_server_properties.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/irods_ssl_object.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/irods_stacktrace.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/irods_state_table.h
	${IRODS_SOURCE_DIR}/lib/core/include/irods_string_tokenize.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/irods_tcp_object.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/irods_threads.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/irods_virtual_path.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/query_builder.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/query_processor.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/lsUtil.h
	${IRODS_SOURCE_DIR}/lib/core/include/mcollUtil.h
	${IRODS_SOURCE_DIR}/lib/core/include/microservice.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/miscUtil.h
	${IRODS_SOURCE_DIR}/lib/core/include/mkdirUtil.h
	${IRODS_SOURCE_DIR}/lib/core/include/msParam.h
	${IRODS_SOURCE_DIR}/lib/core/include/mvUtil.h
	${IRODS_SOURCE_DIR}/lib/core/include/obf.h
	${IRODS_SOURCE_DIR}/lib/core/include/objInfo.h
	${IRODS_SOURCE_DIR}/lib/core/include/osauth.h
	${IRODS_SOURCE_DIR}/lib/core/include/packStruct.h
	${IRODS_SOURCE_DIR}/lib/core/include/parseCommandLine.h
	${IRODS_SOURCE_DIR}/lib/core/include/phybunUtil.h
	${IRODS_SOURCE_DIR}/lib/core/include/phymvUtil.h
	${IRODS_SOURCE_DIR}/lib/core/include/procApiRequest.h
	${IRODS_SOURCE_DIR}/lib/core/include/putUtil.h
	${IRODS_SOURCE_DIR}/lib/core/include/rcConnect.h
	${IRODS_SOURCE_DIR}/lib/core/include/rcGlobalExtern.h
	${IRODS_SOURCE_DIR}/lib/core/include/rcMisc.h
	${IRODS_SOURCE_DIR}/lib/core/include/rcPortalOpr.h
	${IRODS_SOURCE_DIR}/lib/core/include/regUtil.h
	${IRODS_SOURCE_DIR}/lib/core/include/region.h
	${IRODS_SOURCE_DIR}/lib/core/include/replUtil.h
	${IRODS_SOURCE_DIR}/lib/core/include/rmdirUtil.h
	${IRODS_SOURCE_DIR}/lib/core/include/rmUtil.h
	${IRODS_SOURCE_DIR}/lib/core/include/rmtrashUtil.h
	${IRODS_SOURCE_DIR}/lib/core/include/rods.h
	${IRODS_SOURCE_DIR}/lib/core/include/rodsClient.h
	${IRODS_SOURCE_DIR}/lib/core/include/rodsDef.h
	${IRODS_SOURCE_DIR}/lib/core/include/rodsError.h
	${IRODS_SOURCE_DIR}/lib/core/include/rodsErrorTable.h
	${IRODS_SOURCE_DIR}/lib/core/include/rodsGenQuery.h
	${IRODS_SOURCE_DIR}/lib/core/include/rodsGenQueryNames.h
	${IRODS_SOURCE_DIR}/lib/core/include/rodsGeneralUpdate.h
	${IRODS_SOURCE_DIR}/lib/core/include/rodsKeyWdDef.h
	${IRODS_SOURCE_DIR}/lib/core/include/rodsLog.h
	${IRODS_SOURCE_DIR}/lib/core/include/rodsPackInstruct.h
	${IRODS_SOURCE_DIR}/lib/core/include/rodsPackTable.h
	${IRODS_SOURCE_DIR}/lib/core/include/rodsPath.h
	${IRODS_SOURCE_DIR}/lib/core/include/rodsQuota.h
	${IRODS_SOURCE_DIR}/lib/core/include/rodsType.h
	${IRODS_SOURCE_DIR}/lib/core/include/rodsUser.h
	${IRODS_SOURCE_DIR}/lib/core/include/rodsXmsg.h
	${IRODS_SOURCE_DIR}/lib/core/include/rsyncUtil.h
	${IRODS_SOURCE_DIR}/lib/core/include/scanUtil.h
	${IRODS_SOURCE_DIR}/lib/core/include/sockComm.h
	${IRODS_SOURCE_DIR}/lib/core/include/sockCommNetworkInterface.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/socket_wrapper.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/sslSockComm.h
	${IRODS_SOURCE_DIR}/lib/core/include/stringOpr.h
	${IRODS_SOURCE_DIR}/lib/core/include/termiosUtil.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/thread_pool.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/trimUtil.h
)
