set (
	IRODS_SERVER_API_INCLUDE_HEADERS
	${IRODS_SOURCE_DIR}/server/api/include/rsAuthCheck.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsAuthPluginRequest.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsAuthRequest.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsAuthResponse.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsAuthenticate.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsBulkDataObjPut.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsBulkDataObjReg.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsChkNVPathPerm.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsChkObjPermAndStat.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsClientHints.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsCloseCollection.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsCollCreate.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsCollRepl.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsDataCopy.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsDataGet.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsDataObjChksum.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsDataObjClose.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsDataObjCopy.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsDataObjCreate.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsDataObjCreateAndStat.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsDataObjGet.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsDataObjLock.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsDataObjLseek.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsDataObjOpen.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsDataObjOpenAndStat.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsDataObjPhymv.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsDataObjPut.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsDataObjRead.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsDataObjRename.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsDataObjRepl.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsDataObjRsync.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsDataObjTrim.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsDataObjTruncate.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsDataObjUnlink.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsDataObjWrite.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsDataPut.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsEndTransaction.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsExecCmd.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsExecMyRule.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsExecRuleExpression.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsFileChksum.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsFileChmod.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsFileClose.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsFileClosedir.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsFileCreate.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsFileGet.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsFileGetFsFreeSpace.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsFileLseek.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsFileMkdir.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsFileOpen.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsFileOpendir.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsFilePut.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsFileRead.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsFileReaddir.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsFileRename.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsFileRmdir.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsFileStageToCache.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsFileStat.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsFileSyncToArch.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsFileTruncate.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsFileUnlink.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsFileWrite.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsGenQuery.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsGeneralAdmin.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsGeneralRowInsert.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsGeneralRowPurge.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsGeneralUpdate.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsGetHierFromLeafId.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsGetHierarchyForResc.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsGetHostForGet.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsGetHostForPut.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsGetLimitedPassword.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsGetMiscSvrInfo.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsGetRemoteZoneResc.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsGetRescQuota.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsGetTempPassword.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsGetTempPasswordForOther.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsGetXmsgTicket.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsIESClientHints.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsL3FileGetSingleBuf.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsL3FilePutSingleBuf.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsModAVUMetadata.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsModAccessControl.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsModColl.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsModDataObjMeta.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsObjStat.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsOpenCollection.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsOprComplete.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsPamAuthRequest.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsPhyBundleColl.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsPhyPathReg.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsProcStat.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsQuerySpecColl.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsRcvXmsg.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsReadCollection.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsRegColl.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsRegDataObj.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsRegReplica.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsRmColl.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsRuleExecDel.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsRuleExecMod.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsRuleExecSubmit.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsSendXmsg.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsServerReport.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsSetRoundRobinContext.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsSimpleQuery.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsSpecificQuery.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsSslEnd.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsSslStart.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsStreamClose.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsStreamRead.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsStructFileBundle.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsStructFileExtAndReg.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsStructFileExtract.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsStructFileSync.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsSubStructFileClose.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsSubStructFileClosedir.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsSubStructFileCreate.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsSubStructFileGet.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsSubStructFileLseek.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsSubStructFileMkdir.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsSubStructFileOpen.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsSubStructFileOpendir.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsSubStructFilePut.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsSubStructFileRead.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsSubStructFileReaddir.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsSubStructFileRename.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsSubStructFileRmdir.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsSubStructFileStat.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsSubStructFileTruncate.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsSubStructFileUnlink.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsSubStructFileWrite.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsSyncMountedColl.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsTicketAdmin.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsUnbunAndRegPhyBunfile.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsUnregDataObj.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsUserAdmin.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsZoneReport.hpp
)
