set (
	IRODS_LIB_API_INCLUDE_HEADERS
	${IRODS_SOURCE_DIR}/lib/api/include/apiHeaderAll.h
	${IRODS_SOURCE_DIR}/lib/api/include/apiNumber.h
	${IRODS_SOURCE_DIR}/lib/api/include/apiPackTable.h
	${IRODS_SOURCE_DIR}/lib/api/include/apiTable.hpp
	${IRODS_SOURCE_DIR}/lib/api/include/authCheck.h
	${IRODS_SOURCE_DIR}/lib/api/include/authPluginRequest.h
	${IRODS_SOURCE_DIR}/lib/api/include/authRequest.h
	${IRODS_SOURCE_DIR}/lib/api/include/authResponse.h
	${IRODS_SOURCE_DIR}/lib/api/include/authenticate.h
	${IRODS_SOURCE_DIR}/lib/api/include/bulkDataObjPut.h
	${IRODS_SOURCE_DIR}/lib/api/include/bulkDataObjReg.h
	${IRODS_SOURCE_DIR}/lib/api/include/chkNVPathPerm.h
	${IRODS_SOURCE_DIR}/lib/api/include/chkObjPermAndStat.h
	${IRODS_SOURCE_DIR}/lib/api/include/client_hints.h
	${IRODS_SOURCE_DIR}/lib/api/include/closeCollection.h
	${IRODS_SOURCE_DIR}/lib/api/include/collCreate.h
	${IRODS_SOURCE_DIR}/lib/api/include/collRepl.h
	${IRODS_SOURCE_DIR}/lib/api/include/dataCopy.h
	${IRODS_SOURCE_DIR}/lib/api/include/dataGet.h
	${IRODS_SOURCE_DIR}/lib/api/include/dataObjChksum.h
	${IRODS_SOURCE_DIR}/lib/api/include/dataObjClose.h
	${IRODS_SOURCE_DIR}/lib/api/include/dataObjCopy.h
	${IRODS_SOURCE_DIR}/lib/api/include/dataObjCreate.h
	${IRODS_SOURCE_DIR}/lib/api/include/dataObjCreateAndStat.h
	${IRODS_SOURCE_DIR}/lib/api/include/dataObjGet.h
	${IRODS_SOURCE_DIR}/lib/api/include/dataObjInpOut.h
	${IRODS_SOURCE_DIR}/lib/api/include/dataObjLock.h
	${IRODS_SOURCE_DIR}/lib/api/include/dataObjLseek.h
	${IRODS_SOURCE_DIR}/lib/api/include/dataObjOpen.h
	${IRODS_SOURCE_DIR}/lib/api/include/dataObjOpenAndStat.h
	${IRODS_SOURCE_DIR}/lib/api/include/dataObjPhymv.h
	${IRODS_SOURCE_DIR}/lib/api/include/dataObjPut.h
	${IRODS_SOURCE_DIR}/lib/api/include/dataObjRead.h
	${IRODS_SOURCE_DIR}/lib/api/include/dataObjRename.h
	${IRODS_SOURCE_DIR}/lib/api/include/dataObjRepl.h
	${IRODS_SOURCE_DIR}/lib/api/include/dataObjRsync.h
	${IRODS_SOURCE_DIR}/lib/api/include/dataObjTrim.h
	${IRODS_SOURCE_DIR}/lib/api/include/dataObjTruncate.h
	${IRODS_SOURCE_DIR}/lib/api/include/dataObjUnlink.h
	${IRODS_SOURCE_DIR}/lib/api/include/dataObjWrite.h
	${IRODS_SOURCE_DIR}/lib/api/include/dataPut.h
	${IRODS_SOURCE_DIR}/lib/api/include/endTransaction.h
	${IRODS_SOURCE_DIR}/lib/api/include/execCmd.h
	${IRODS_SOURCE_DIR}/lib/api/include/execMyRule.h
	${IRODS_SOURCE_DIR}/lib/api/include/exec_rule_expression.h
	${IRODS_SOURCE_DIR}/lib/api/include/fileChksum.h
	${IRODS_SOURCE_DIR}/lib/api/include/fileChmod.h
	${IRODS_SOURCE_DIR}/lib/api/include/fileClose.h
	${IRODS_SOURCE_DIR}/lib/api/include/fileClosedir.h
	${IRODS_SOURCE_DIR}/lib/api/include/fileCreate.h
	${IRODS_SOURCE_DIR}/lib/api/include/fileGet.h
	${IRODS_SOURCE_DIR}/lib/api/include/fileGetFsFreeSpace.h
	${IRODS_SOURCE_DIR}/lib/api/include/fileLseek.h
	${IRODS_SOURCE_DIR}/lib/api/include/fileMkdir.h
	${IRODS_SOURCE_DIR}/lib/api/include/fileOpen.h
	${IRODS_SOURCE_DIR}/lib/api/include/fileOpendir.h
	${IRODS_SOURCE_DIR}/lib/api/include/filePut.h
	${IRODS_SOURCE_DIR}/lib/api/include/fileRead.h
	${IRODS_SOURCE_DIR}/lib/api/include/fileReaddir.h
	${IRODS_SOURCE_DIR}/lib/api/include/fileRename.h
	${IRODS_SOURCE_DIR}/lib/api/include/fileRmdir.h
	${IRODS_SOURCE_DIR}/lib/api/include/fileStageToCache.h
	${IRODS_SOURCE_DIR}/lib/api/include/fileStat.h
	${IRODS_SOURCE_DIR}/lib/api/include/fileSyncToArch.h
	${IRODS_SOURCE_DIR}/lib/api/include/fileTruncate.h
	${IRODS_SOURCE_DIR}/lib/api/include/fileUnlink.h
	${IRODS_SOURCE_DIR}/lib/api/include/fileWrite.h
	${IRODS_SOURCE_DIR}/lib/api/include/genQuery.h
	${IRODS_SOURCE_DIR}/lib/api/include/generalAdmin.h
	${IRODS_SOURCE_DIR}/lib/api/include/generalRowInsert.h
	${IRODS_SOURCE_DIR}/lib/api/include/generalRowPurge.h
	${IRODS_SOURCE_DIR}/lib/api/include/generalUpdate.h
	${IRODS_SOURCE_DIR}/lib/api/include/getHierarchyForResc.h
	${IRODS_SOURCE_DIR}/lib/api/include/getHostForGet.h
	${IRODS_SOURCE_DIR}/lib/api/include/getHostForPut.h
	${IRODS_SOURCE_DIR}/lib/api/include/getLimitedPassword.h
	${IRODS_SOURCE_DIR}/lib/api/include/getMiscSvrInfo.h
	${IRODS_SOURCE_DIR}/lib/api/include/getRemoteZoneResc.h
	${IRODS_SOURCE_DIR}/lib/api/include/getRescQuota.h
	${IRODS_SOURCE_DIR}/lib/api/include/getTempPassword.h
	${IRODS_SOURCE_DIR}/lib/api/include/getTempPasswordForOther.h
	${IRODS_SOURCE_DIR}/lib/api/include/getXmsgTicket.h
	${IRODS_SOURCE_DIR}/lib/api/include/get_hier_from_leaf_id.h
	${IRODS_SOURCE_DIR}/lib/api/include/ies_client_hints.h
	${IRODS_SOURCE_DIR}/lib/api/include/l3FileGetSingleBuf.h
	${IRODS_SOURCE_DIR}/lib/api/include/l3FilePutSingleBuf.h
	${IRODS_SOURCE_DIR}/lib/api/include/modAVUMetadata.h
	${IRODS_SOURCE_DIR}/lib/api/include/modAccessControl.h
	${IRODS_SOURCE_DIR}/lib/api/include/modColl.h
	${IRODS_SOURCE_DIR}/lib/api/include/modDataObjMeta.h
	${IRODS_SOURCE_DIR}/lib/api/include/objStat.h
	${IRODS_SOURCE_DIR}/lib/api/include/openCollection.h
	${IRODS_SOURCE_DIR}/lib/api/include/oprComplete.h
	${IRODS_SOURCE_DIR}/lib/api/include/pamAuthRequest.h
	${IRODS_SOURCE_DIR}/lib/api/include/phyBundleColl.h
	${IRODS_SOURCE_DIR}/lib/api/include/phyPathReg.h
	${IRODS_SOURCE_DIR}/lib/api/include/procStat.h
	${IRODS_SOURCE_DIR}/lib/api/include/querySpecColl.h
	${IRODS_SOURCE_DIR}/lib/api/include/rcvXmsg.h
	${IRODS_SOURCE_DIR}/lib/api/include/readCollection.h
	${IRODS_SOURCE_DIR}/lib/api/include/regColl.h
	${IRODS_SOURCE_DIR}/lib/api/include/regDataObj.h
	${IRODS_SOURCE_DIR}/lib/api/include/regReplica.h
	${IRODS_SOURCE_DIR}/lib/api/include/rmColl.h
	${IRODS_SOURCE_DIR}/lib/api/include/ruleExecDel.h
	${IRODS_SOURCE_DIR}/lib/api/include/ruleExecMod.h
	${IRODS_SOURCE_DIR}/lib/api/include/ruleExecSubmit.h
	${IRODS_SOURCE_DIR}/lib/api/include/sendXmsg.h
	${IRODS_SOURCE_DIR}/lib/api/include/server_report.h
	${IRODS_SOURCE_DIR}/lib/api/include/set_round_robin_context.h
	${IRODS_SOURCE_DIR}/lib/api/include/simpleQuery.h
	${IRODS_SOURCE_DIR}/lib/api/include/specificQuery.h
	${IRODS_SOURCE_DIR}/lib/api/include/sslEnd.h
	${IRODS_SOURCE_DIR}/lib/api/include/sslStart.h
	${IRODS_SOURCE_DIR}/lib/api/include/streamClose.h
	${IRODS_SOURCE_DIR}/lib/api/include/streamRead.h
	${IRODS_SOURCE_DIR}/lib/api/include/structFileBundle.h
	${IRODS_SOURCE_DIR}/lib/api/include/structFileExtAndReg.h
	${IRODS_SOURCE_DIR}/lib/api/include/structFileExtract.h
	${IRODS_SOURCE_DIR}/lib/api/include/structFileSync.h
	${IRODS_SOURCE_DIR}/lib/api/include/subStructFileClose.h
	${IRODS_SOURCE_DIR}/lib/api/include/subStructFileClosedir.h
	${IRODS_SOURCE_DIR}/lib/api/include/subStructFileCreate.h
	${IRODS_SOURCE_DIR}/lib/api/include/subStructFileGet.h
	${IRODS_SOURCE_DIR}/lib/api/include/subStructFileLseek.h
	${IRODS_SOURCE_DIR}/lib/api/include/subStructFileMkdir.h
	${IRODS_SOURCE_DIR}/lib/api/include/subStructFileOpen.h
	${IRODS_SOURCE_DIR}/lib/api/include/subStructFileOpendir.h
	${IRODS_SOURCE_DIR}/lib/api/include/subStructFilePut.h
	${IRODS_SOURCE_DIR}/lib/api/include/subStructFileRead.h
	${IRODS_SOURCE_DIR}/lib/api/include/subStructFileReaddir.h
	${IRODS_SOURCE_DIR}/lib/api/include/subStructFileRename.h
	${IRODS_SOURCE_DIR}/lib/api/include/subStructFileRmdir.h
	${IRODS_SOURCE_DIR}/lib/api/include/subStructFileStat.h
	${IRODS_SOURCE_DIR}/lib/api/include/subStructFileTruncate.h
	${IRODS_SOURCE_DIR}/lib/api/include/subStructFileUnlink.h
	${IRODS_SOURCE_DIR}/lib/api/include/subStructFileWrite.h
	${IRODS_SOURCE_DIR}/lib/api/include/syncMountedColl.h
	${IRODS_SOURCE_DIR}/lib/api/include/ticketAdmin.h
	${IRODS_SOURCE_DIR}/lib/api/include/unbunAndRegPhyBunfile.h
	${IRODS_SOURCE_DIR}/lib/api/include/unregDataObj.h
	${IRODS_SOURCE_DIR}/lib/api/include/userAdmin.h
	${IRODS_SOURCE_DIR}/lib/api/include/zone_report.h
)
