set (
	IRODS_LIB_CORE_SOURCES
	${IRODS_SOURCE_DIR}/lib/core/src/apiHandler.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/base64.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/bunUtil.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/chksumUtil.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/clientLogin.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/cpUtil.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/fsckUtil.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/getRodsEnv.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/getUtil.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/hashtable.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/irods_auth_factory.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/irods_auth_manager.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/irods_auth_object.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/irods_generic_auth_object.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/irods_buffer_encryption.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/irods_children_parser.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/irods_c_api.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/irods_client_api_table.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/irods_client_negotiation.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/irods_configuration_parser.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/irods_default_paths.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/irods_environment_properties.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/irods_error.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/irods_exception.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/irods_get_full_path_for_config_file.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/irods_gsi_object.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/irods_hierarchy_parser.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/irods_krb_object.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/irods_kvp_string_parser.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/irods_log.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/irods_native_auth_object.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/irods_network_factory.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/irods_network_manager.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/irods_network_object.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/irods_osauth_auth_object.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/irods_pack_table.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/irods_pam_auth_object.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/irods_parse_command_line_options.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/irods_path_recursion.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/irods_pluggable_auth_scheme.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/irods_plugin_name_generator.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/irods_random.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/irods_serialization.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/irods_server_properties.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/irods_socket_information.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/irods_ssl_object.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/irods_stacktrace.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/irods_string_tokenize.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/irods_tcp_object.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/irods_virtual_path.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/list.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/lsUtil.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/mcollUtil.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/miscUtil.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/mkdirUtil.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/msParam.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/mvUtil.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/obf.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/osauth.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/packStruct.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/parseCommandLine.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/phybunUtil.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/phymvUtil.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/procApiRequest.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/putUtil.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/rcConnect.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/rcGlobal.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/rcMisc.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/rcPortalOpr.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/regUtil.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/region.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/replUtil.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/rmdirUtil.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/rmUtil.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/rmtrashUtil.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/rodsLog.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/rodsPath.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/rsyncUtil.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/scanUtil.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/sockComm.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/sslSockComm.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/stringOpr.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/trimUtil.cpp
)
