#====================
#RodsAPIs library
#====================
set(
	IRODS_LIB_CORE_SOURCES
	${IRODS_SOURCE_DIR}/lib/core/src/apiHandler.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/base64.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/bunUtil.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/chksumUtil.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/clientLogin.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/cpUtil.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/fsckUtil.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/getRodsEnv.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/getUtil.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/hashtable.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/irods_auth_factory.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/irods_auth_manager.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/irods_auth_object.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/irods_generic_auth_object.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/irods_buffer_encryption.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/irods_children_parser.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/irods_c_api.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/irods_client_api_table.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/irods_client_negotiation.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/irods_configuration_parser.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/irods_default_paths.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/irods_environment_properties.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/irods_error.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/irods_exception.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/irods_get_full_path_for_config_file.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/irods_gsi_object.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/irods_hierarchy_parser.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/irods_krb_object.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/irods_kvp_string_parser.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/irods_log.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/irods_native_auth_object.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/irods_network_factory.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/irods_network_manager.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/irods_network_object.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/irods_osauth_auth_object.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/irods_pack_table.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/irods_pam_auth_object.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/irods_parse_command_line_options.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/irods_pluggable_auth_scheme.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/irods_plugin_name_generator.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/irods_random.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/irods_serialization.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/irods_server_properties.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/irods_socket_information.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/irods_ssl_object.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/irods_stacktrace.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/irods_string_tokenize.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/irods_tcp_object.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/irods_virtual_path.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/list.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/lsUtil.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/mcollUtil.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/miscUtil.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/mkdirUtil.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/msParam.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/mvUtil.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/obf.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/osauth.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/packStruct.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/parseCommandLine.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/phybunUtil.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/phymvUtil.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/procApiRequest.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/putUtil.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/rcConnect.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/rcGlobal.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/rcMisc.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/rcPortalOpr.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/regUtil.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/region.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/replUtil.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/rmdirUtil.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/rmUtil.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/rmtrashUtil.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/rodsLog.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/rodsPath.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/rsyncUtil.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/scanUtil.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/sockComm.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/sslSockComm.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/stringOpr.cpp
	${IRODS_SOURCE_DIR}/lib/core/src/trimUtil.cpp
)

set(
	IRODS_LIB_API_SOURCES
	${IRODS_SOURCE_DIR}/lib/api/src/rcGetMiscSvrInfo.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcFileCreate.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcFileOpen.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcFileWrite.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcFileClose.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcFileLseek.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcFileRead.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcFileUnlink.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcFileMkdir.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcFileChmod.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcFileRmdir.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcFileStat.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcFileGetFsFreeSpace.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcFileOpendir.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcFileClosedir.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcFileReaddir.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcDataObjCreate.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcDataObjOpen.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcDataObjRead.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcDataObjWrite.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcDataObjClose.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcDataObjPut.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcDataPut.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcDataObjGet.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcDataGet.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcDataObjRepl.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcFilePut.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcFileGet.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcDataCopy.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcDataObjLseek.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcDataObjCopy.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcSimpleQuery.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcDataObjUnlink.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcCollCreate.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcGeneralAdmin.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcFileChksum.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcChkNVPathPerm.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcGenQuery.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcAuthRequest.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcAuthResponse.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcAuthCheck.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcRegColl.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcRegDataObj.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcUnregDataObj.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcRegReplica.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcModDataObjMeta.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcModAVUMetadata.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcFileRename.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcModAccessControl.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcRuleExecSubmit.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcExecRuleExpression.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcRuleExecDel.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcRuleExecMod.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcExecMyRule.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcOprComplete.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcDataObjRename.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcDataObjRsync.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcDataObjChksum.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcPhyPathReg.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcDataObjPhymv.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcDataObjTrim.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcObjStat.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcExecCmd.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcSubStructFileCreate.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcSubStructFileOpen.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcSubStructFileRead.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcSubStructFileWrite.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcSubStructFileClose.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcSubStructFileUnlink.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcSubStructFileStat.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcSubStructFileLseek.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcSubStructFileRename.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcQuerySpecColl.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcGetTempPassword.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcModColl.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcSubStructFileMkdir.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcSubStructFileRmdir.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcSubStructFileOpendir.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcSubStructFileReaddir.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcSubStructFileClosedir.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcGeneralUpdate.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcGetXmsgTicket.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcSendXmsg.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcRcvXmsg.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcSubStructFileGet.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcSubStructFilePut.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcSyncMountedColl.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcStructFileSync.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcOpenCollection.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcReadCollection.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcCloseCollection.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcCollRepl.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcRmColl.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcStructFileExtract.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcStructFileExtAndReg.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcStructFileBundle.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcChkObjPermAndStat.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcUserAdmin.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcGetRemoteZoneResc.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcDataObjOpenAndStat.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcL3FileGetSingleBuf.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcL3FilePutSingleBuf.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcDataObjCreateAndStat.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcFileStageToCache.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcFileSyncToArch.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcGeneralRowInsert.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcGeneralRowPurge.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcPhyBundleColl.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcUnbunAndRegPhyBunfile.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcGetHostForPut.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcGetRescQuota.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcBulkDataObjReg.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcBulkDataObjPut.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcEndTransaction.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcProcStat.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcStreamRead.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcSpecificQuery.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcStreamClose.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcGetHostForGet.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcDataObjLock.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcTicketAdmin.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcGetTempPasswordForOther.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcPamAuthRequest.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcSslStart.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcSslEnd.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcDataObjTruncate.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcFileTruncate.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcSubStructFileTruncate.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcAuthPluginRequest.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcGetLimitedPassword.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcGetHierarchyForResc.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcServerReport.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcZoneReport.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcClientHints.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcGetHierFromLeafId.cpp
	${IRODS_SOURCE_DIR}/lib/api/src/rcIESClientHints.cpp
)

set(
	IRODS_LIB_RBUDP_SOURCES
	${IRODS_SOURCE_DIR}/lib/rbudp/src/QUANTAnet_rbudpBase_c.cpp
	${IRODS_SOURCE_DIR}/lib/rbudp/src/QUANTAnet_rbudpReceiver_c.cpp
	${IRODS_SOURCE_DIR}/lib/rbudp/src/QUANTAnet_rbudpSender_c.cpp
)

set(
	IRODS_LIB_HASHER_SOURCES
	${IRODS_SOURCE_DIR}/lib/hasher/src/Hasher.cpp
	${IRODS_SOURCE_DIR}/lib/hasher/src/MD5Strategy.cpp
	${IRODS_SOURCE_DIR}/lib/hasher/src/SHA256Strategy.cpp
	${IRODS_SOURCE_DIR}/lib/hasher/src/checksum.cpp
	${IRODS_SOURCE_DIR}/lib/hasher/src/irods_hasher_factory.cpp
)

set(
	IRODS_LIB_CLIENT_EXEC_SOURCES
)

add_library(
	RodsAPIs
	STATIC
	${IRODS_LIB_CORE_SOURCES}
	${IRODS_LIB_API_SOURCES}
	${IRODS_LIB_RBUDP_SOURCES}
	${IRODS_LIB_HASHER_SOURCES}
	${IRODS_LIB_CLIENT_EXEC_SOURCES}
)

target_include_directories(
	RodsAPIs
	PRIVATE
	${CMAKE_BINARY_DIR}/lib/core/include
	${IRODS_SOURCE_DIR}/lib/core/include
	${IRODS_SOURCE_DIR}/lib/api/include
	${IRODS_SOURCE_DIR}/lib/hasher/include
	${IRODS_SOURCE_DIR}/lib/rbudp/include
	${IRODS_SOURCE_DIR}/server/core/include
	${IRODS_SOURCE_DIR}/server/icat/include
	${IRODS_SOURCE_DIR}/server/re/include
	${IRODS_SOURCE_DIR}/server/drivers/include
	${Boost_INCLUDE_DIRS}
	${JANSSON_INCLUDE_DIRS}
	${OPENSSL_INCLUDE_DIR}
)

target_link_libraries(
	RodsAPIs
	PRIVATE
	${Boost_CHRONO_LIBRARY}
	${Boost_FILESYSTEM_LIBRARY}
	${Boost_REGEX_LIBRARY}
	${Boost_SYSTEM_LIBRARY}
	${Boost_THREAD_LIBRARY}
	${JANSSON_LIBRARIES}
	${OPENSSL_SSL_LIBRARY}
	${OPENSSL_CRYPTO_LIBRARY}
	${CMAKE_DL_LIBS}
)

set_property( TARGET RodsAPIs PROPERTY CXX_STANDARD ${IRODS_CXX_STANDARD} )
target_compile_definitions( RodsAPIs PRIVATE ${IRODS_COMPILE_DEFINITIONS} )
target_compile_options( RodsAPIs PRIVATE -Wno-write-strings )

install(
	TARGETS
	RodsAPIs
	ARCHIVE
	DESTINATION ${IRODS_LIBRARY_DIR}
	COMPONENT irods-development
	# COMPONENT ${IRODS_PACKAGE_COMPONENT_DEVELOPMENT_NAME}
)

set(
	IRODS_GENERATED_HEADERS
	${CMAKE_BINARY_DIR}/lib/core/include/irods_version.h
	${CMAKE_BINARY_DIR}/lib/core/include/rodsVersion.h
	${CMAKE_BINARY_DIR}/lib/core/include/server_control_plane_command.hpp
)

set(
	IRODS_LIB_CORE_INCLUDE_HEADERS
	${IRODS_SOURCE_DIR}/lib/core/include/apiHandler.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/base64.h
	${IRODS_SOURCE_DIR}/lib/core/include/bunUtil.h
	${IRODS_SOURCE_DIR}/lib/core/include/chksumUtil.h
	${IRODS_SOURCE_DIR}/lib/core/include/cpUtil.h
	${IRODS_SOURCE_DIR}/lib/core/include/fsckUtil.h
	${IRODS_SOURCE_DIR}/lib/core/include/getRodsEnv.h
	${IRODS_SOURCE_DIR}/lib/core/include/getUtil.h
	${IRODS_SOURCE_DIR}/lib/core/include/guiProgressCallback.h
	${IRODS_SOURCE_DIR}/lib/core/include/irods_assert.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/irods_auth_constants.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/irods_auth_factory.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/irods_auth_manager.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/irods_auth_object.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/irods_generic_auth_object.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/irods_auth_plugin.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/irods_auth_types.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/irods_buffer_encryption.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/irods_children_parser.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/irods_client_api_table.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/irods_client_server_negotiation.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/irods_configuration_keywords.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/irods_configuration_parser.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/irods_default_paths.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/irods_environment_properties.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/irods_error.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/irods_exception.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/irods_first_class_object.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/irods_get_full_path_for_config_file.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/irods_gsi_object.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/irods_hash.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/irods_hashtable.h
	${IRODS_SOURCE_DIR}/lib/core/include/irods_hierarchy_parser.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/irods_krb_object.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/irods_kvp_string_parser.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/irods_lexical_cast.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/irods_list.h
	${IRODS_SOURCE_DIR}/lib/core/include/irods_load_plugin.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/irods_log.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/irods_lookup_table.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/irods_native_auth_object.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/irods_network_constants.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/irods_network_factory.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/irods_network_manager.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/irods_network_object.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/irods_network_plugin.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/irods_network_types.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/irods_osauth_auth_object.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/irods_pack_table.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/irods_pam_auth_object.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/irods_parse_command_line_options.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/irods_pluggable_auth_scheme.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/irods_plugin_base.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/irods_plugin_context.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/irods_plugin_name_generator.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/irods_random.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/irods_serialization.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/irods_server_properties.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/irods_ssl_object.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/irods_stacktrace.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/irods_string_tokenize.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/irods_tcp_object.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/irods_threads.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/irods_virtual_path.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/lsUtil.h
	${IRODS_SOURCE_DIR}/lib/core/include/mcollUtil.h
	${IRODS_SOURCE_DIR}/lib/core/include/microservice.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/miscUtil.h
	${IRODS_SOURCE_DIR}/lib/core/include/mkdirUtil.h
	${IRODS_SOURCE_DIR}/lib/core/include/msParam.h
	${IRODS_SOURCE_DIR}/lib/core/include/mvUtil.h
	${IRODS_SOURCE_DIR}/lib/core/include/obf.h
	${IRODS_SOURCE_DIR}/lib/core/include/objInfo.h
	${IRODS_SOURCE_DIR}/lib/core/include/osauth.h
	${IRODS_SOURCE_DIR}/lib/core/include/packStruct.h
	${IRODS_SOURCE_DIR}/lib/core/include/parseCommandLine.h
	${IRODS_SOURCE_DIR}/lib/core/include/phybunUtil.h
	${IRODS_SOURCE_DIR}/lib/core/include/phymvUtil.h
	${IRODS_SOURCE_DIR}/lib/core/include/procApiRequest.h
	${IRODS_SOURCE_DIR}/lib/core/include/putUtil.h
	${IRODS_SOURCE_DIR}/lib/core/include/rcConnect.h
	${IRODS_SOURCE_DIR}/lib/core/include/rcGlobalExtern.h
	${IRODS_SOURCE_DIR}/lib/core/include/rcMisc.h
	${IRODS_SOURCE_DIR}/lib/core/include/rcPortalOpr.h
	${IRODS_SOURCE_DIR}/lib/core/include/regUtil.h
	${IRODS_SOURCE_DIR}/lib/core/include/region.h
	${IRODS_SOURCE_DIR}/lib/core/include/replUtil.h
	${IRODS_SOURCE_DIR}/lib/core/include/rmdirUtil.h
	${IRODS_SOURCE_DIR}/lib/core/include/rmUtil.h
	${IRODS_SOURCE_DIR}/lib/core/include/rmtrashUtil.h
	${IRODS_SOURCE_DIR}/lib/core/include/rods.h
	${IRODS_SOURCE_DIR}/lib/core/include/rodsClient.h
	${IRODS_SOURCE_DIR}/lib/core/include/rodsDef.h
	${IRODS_SOURCE_DIR}/lib/core/include/rodsError.h
	${IRODS_SOURCE_DIR}/lib/core/include/rodsErrorTable.h
	${IRODS_SOURCE_DIR}/lib/core/include/rodsGenQuery.h
	${IRODS_SOURCE_DIR}/lib/core/include/rodsGenQueryNames.h
	${IRODS_SOURCE_DIR}/lib/core/include/rodsGeneralUpdate.h
	${IRODS_SOURCE_DIR}/lib/core/include/rodsKeyWdDef.h
	${IRODS_SOURCE_DIR}/lib/core/include/rodsLog.h
	${IRODS_SOURCE_DIR}/lib/core/include/rodsPackInstruct.h
	${IRODS_SOURCE_DIR}/lib/core/include/rodsPackTable.h
	${IRODS_SOURCE_DIR}/lib/core/include/rodsPath.h
	${IRODS_SOURCE_DIR}/lib/core/include/rodsQuota.h
	${IRODS_SOURCE_DIR}/lib/core/include/rodsType.h
	${IRODS_SOURCE_DIR}/lib/core/include/rodsUser.h
	${IRODS_SOURCE_DIR}/lib/core/include/rodsXmsg.h
	${IRODS_SOURCE_DIR}/lib/core/include/rsyncUtil.h
	${IRODS_SOURCE_DIR}/lib/core/include/scanUtil.h
	${IRODS_SOURCE_DIR}/lib/core/include/sockComm.h
	${IRODS_SOURCE_DIR}/lib/core/include/sockCommNetworkInterface.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/socket_wrapper.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/sslSockComm.h
	${IRODS_SOURCE_DIR}/lib/core/include/stringOpr.h
	${IRODS_SOURCE_DIR}/lib/core/include/termiosUtil.hpp
	${IRODS_SOURCE_DIR}/lib/core/include/trimUtil.h
)

set(
	IRODS_LIB_HASHER_INCLUDE_HEADERS
	${IRODS_SOURCE_DIR}/lib/hasher/include/HashStrategy.hpp
	${IRODS_SOURCE_DIR}/lib/hasher/include/Hasher.hpp
	${IRODS_SOURCE_DIR}/lib/hasher/include/MD5Strategy.hpp
	${IRODS_SOURCE_DIR}/lib/hasher/include/SHA256Strategy.hpp
	${IRODS_SOURCE_DIR}/lib/hasher/include/checksum.hpp
	${IRODS_SOURCE_DIR}/lib/hasher/include/irods_hasher_factory.hpp
)

set(
	IRODS_LIB_API_INCLUDE_HEADERS
	${IRODS_SOURCE_DIR}/lib/api/include/apiHeaderAll.h
	${IRODS_SOURCE_DIR}/lib/api/include/apiNumber.h
	${IRODS_SOURCE_DIR}/lib/api/include/apiPackTable.h
	${IRODS_SOURCE_DIR}/lib/api/include/apiTable.hpp
	${IRODS_SOURCE_DIR}/lib/api/include/authCheck.h
	${IRODS_SOURCE_DIR}/lib/api/include/authPluginRequest.h
	${IRODS_SOURCE_DIR}/lib/api/include/authRequest.h
	${IRODS_SOURCE_DIR}/lib/api/include/authResponse.h
	${IRODS_SOURCE_DIR}/lib/api/include/authenticate.h
	${IRODS_SOURCE_DIR}/lib/api/include/bulkDataObjPut.h
	${IRODS_SOURCE_DIR}/lib/api/include/bulkDataObjReg.h
	${IRODS_SOURCE_DIR}/lib/api/include/chkNVPathPerm.h
	${IRODS_SOURCE_DIR}/lib/api/include/chkObjPermAndStat.h
	${IRODS_SOURCE_DIR}/lib/api/include/client_hints.h
	${IRODS_SOURCE_DIR}/lib/api/include/closeCollection.h
	${IRODS_SOURCE_DIR}/lib/api/include/collCreate.h
	${IRODS_SOURCE_DIR}/lib/api/include/collRepl.h
	${IRODS_SOURCE_DIR}/lib/api/include/dataCopy.h
	${IRODS_SOURCE_DIR}/lib/api/include/dataGet.h
	${IRODS_SOURCE_DIR}/lib/api/include/dataObjChksum.h
	${IRODS_SOURCE_DIR}/lib/api/include/dataObjClose.h
	${IRODS_SOURCE_DIR}/lib/api/include/dataObjCopy.h
	${IRODS_SOURCE_DIR}/lib/api/include/dataObjCreate.h
	${IRODS_SOURCE_DIR}/lib/api/include/dataObjCreateAndStat.h
	${IRODS_SOURCE_DIR}/lib/api/include/dataObjGet.h
	${IRODS_SOURCE_DIR}/lib/api/include/dataObjInpOut.h
	${IRODS_SOURCE_DIR}/lib/api/include/dataObjLock.h
	${IRODS_SOURCE_DIR}/lib/api/include/dataObjLseek.h
	${IRODS_SOURCE_DIR}/lib/api/include/dataObjOpen.h
	${IRODS_SOURCE_DIR}/lib/api/include/dataObjOpenAndStat.h
	${IRODS_SOURCE_DIR}/lib/api/include/dataObjPhymv.h
	${IRODS_SOURCE_DIR}/lib/api/include/dataObjPut.h
	${IRODS_SOURCE_DIR}/lib/api/include/dataObjRead.h
	${IRODS_SOURCE_DIR}/lib/api/include/dataObjRename.h
	${IRODS_SOURCE_DIR}/lib/api/include/dataObjRepl.h
	${IRODS_SOURCE_DIR}/lib/api/include/dataObjRsync.h
	${IRODS_SOURCE_DIR}/lib/api/include/dataObjTrim.h
	${IRODS_SOURCE_DIR}/lib/api/include/dataObjTruncate.h
	${IRODS_SOURCE_DIR}/lib/api/include/dataObjUnlink.h
	${IRODS_SOURCE_DIR}/lib/api/include/dataObjWrite.h
	${IRODS_SOURCE_DIR}/lib/api/include/dataPut.h
	${IRODS_SOURCE_DIR}/lib/api/include/endTransaction.h
	${IRODS_SOURCE_DIR}/lib/api/include/execCmd.h
	${IRODS_SOURCE_DIR}/lib/api/include/execMyRule.h
	${IRODS_SOURCE_DIR}/lib/api/include/exec_rule_expression.h
	${IRODS_SOURCE_DIR}/lib/api/include/fileChksum.h
	${IRODS_SOURCE_DIR}/lib/api/include/fileChmod.h
	${IRODS_SOURCE_DIR}/lib/api/include/fileClose.h
	${IRODS_SOURCE_DIR}/lib/api/include/fileClosedir.h
	${IRODS_SOURCE_DIR}/lib/api/include/fileCreate.h
	${IRODS_SOURCE_DIR}/lib/api/include/fileGet.h
	${IRODS_SOURCE_DIR}/lib/api/include/fileGetFsFreeSpace.h
	${IRODS_SOURCE_DIR}/lib/api/include/fileLseek.h
	${IRODS_SOURCE_DIR}/lib/api/include/fileMkdir.h
	${IRODS_SOURCE_DIR}/lib/api/include/fileOpen.h
	${IRODS_SOURCE_DIR}/lib/api/include/fileOpendir.h
	${IRODS_SOURCE_DIR}/lib/api/include/filePut.h
	${IRODS_SOURCE_DIR}/lib/api/include/fileRead.h
	${IRODS_SOURCE_DIR}/lib/api/include/fileReaddir.h
	${IRODS_SOURCE_DIR}/lib/api/include/fileRename.h
	${IRODS_SOURCE_DIR}/lib/api/include/fileRmdir.h
	${IRODS_SOURCE_DIR}/lib/api/include/fileStageToCache.h
	${IRODS_SOURCE_DIR}/lib/api/include/fileStat.h
	${IRODS_SOURCE_DIR}/lib/api/include/fileSyncToArch.h
	${IRODS_SOURCE_DIR}/lib/api/include/fileTruncate.h
	${IRODS_SOURCE_DIR}/lib/api/include/fileUnlink.h
	${IRODS_SOURCE_DIR}/lib/api/include/fileWrite.h
	${IRODS_SOURCE_DIR}/lib/api/include/genQuery.h
	${IRODS_SOURCE_DIR}/lib/api/include/generalAdmin.h
	${IRODS_SOURCE_DIR}/lib/api/include/generalRowInsert.h
	${IRODS_SOURCE_DIR}/lib/api/include/generalRowPurge.h
	${IRODS_SOURCE_DIR}/lib/api/include/generalUpdate.h
	${IRODS_SOURCE_DIR}/lib/api/include/getHierarchyForResc.h
	${IRODS_SOURCE_DIR}/lib/api/include/getHostForGet.h
	${IRODS_SOURCE_DIR}/lib/api/include/getHostForPut.h
	${IRODS_SOURCE_DIR}/lib/api/include/getLimitedPassword.h
	${IRODS_SOURCE_DIR}/lib/api/include/getMiscSvrInfo.h
	${IRODS_SOURCE_DIR}/lib/api/include/getRemoteZoneResc.h
	${IRODS_SOURCE_DIR}/lib/api/include/getRescQuota.h
	${IRODS_SOURCE_DIR}/lib/api/include/getTempPassword.h
	${IRODS_SOURCE_DIR}/lib/api/include/getTempPasswordForOther.h
	${IRODS_SOURCE_DIR}/lib/api/include/getXmsgTicket.h
	${IRODS_SOURCE_DIR}/lib/api/include/get_hier_from_leaf_id.h
	${IRODS_SOURCE_DIR}/lib/api/include/ies_client_hints.h
	${IRODS_SOURCE_DIR}/lib/api/include/l3FileGetSingleBuf.h
	${IRODS_SOURCE_DIR}/lib/api/include/l3FilePutSingleBuf.h
	${IRODS_SOURCE_DIR}/lib/api/include/modAVUMetadata.h
	${IRODS_SOURCE_DIR}/lib/api/include/modAccessControl.h
	${IRODS_SOURCE_DIR}/lib/api/include/modColl.h
	${IRODS_SOURCE_DIR}/lib/api/include/modDataObjMeta.h
	${IRODS_SOURCE_DIR}/lib/api/include/objStat.h
	${IRODS_SOURCE_DIR}/lib/api/include/openCollection.h
	${IRODS_SOURCE_DIR}/lib/api/include/oprComplete.h
	${IRODS_SOURCE_DIR}/lib/api/include/pamAuthRequest.h
	${IRODS_SOURCE_DIR}/lib/api/include/phyBundleColl.h
	${IRODS_SOURCE_DIR}/lib/api/include/phyPathReg.h
	${IRODS_SOURCE_DIR}/lib/api/include/procStat.h
	${IRODS_SOURCE_DIR}/lib/api/include/querySpecColl.h
	${IRODS_SOURCE_DIR}/lib/api/include/rcvXmsg.h
	${IRODS_SOURCE_DIR}/lib/api/include/readCollection.h
	${IRODS_SOURCE_DIR}/lib/api/include/regColl.h
	${IRODS_SOURCE_DIR}/lib/api/include/regDataObj.h
	${IRODS_SOURCE_DIR}/lib/api/include/regReplica.h
	${IRODS_SOURCE_DIR}/lib/api/include/rmColl.h
	${IRODS_SOURCE_DIR}/lib/api/include/ruleExecDel.h
	${IRODS_SOURCE_DIR}/lib/api/include/ruleExecMod.h
	${IRODS_SOURCE_DIR}/lib/api/include/ruleExecSubmit.h
	${IRODS_SOURCE_DIR}/lib/api/include/sendXmsg.h
	${IRODS_SOURCE_DIR}/lib/api/include/server_report.h
	${IRODS_SOURCE_DIR}/lib/api/include/set_round_robin_context.h
	${IRODS_SOURCE_DIR}/lib/api/include/simpleQuery.h
	${IRODS_SOURCE_DIR}/lib/api/include/specificQuery.h
	${IRODS_SOURCE_DIR}/lib/api/include/sslEnd.h
	${IRODS_SOURCE_DIR}/lib/api/include/sslStart.h
	${IRODS_SOURCE_DIR}/lib/api/include/streamClose.h
	${IRODS_SOURCE_DIR}/lib/api/include/streamRead.h
	${IRODS_SOURCE_DIR}/lib/api/include/structFileBundle.h
	${IRODS_SOURCE_DIR}/lib/api/include/structFileExtAndReg.h
	${IRODS_SOURCE_DIR}/lib/api/include/structFileExtract.h
	${IRODS_SOURCE_DIR}/lib/api/include/structFileSync.h
	${IRODS_SOURCE_DIR}/lib/api/include/subStructFileClose.h
	${IRODS_SOURCE_DIR}/lib/api/include/subStructFileClosedir.h
	${IRODS_SOURCE_DIR}/lib/api/include/subStructFileCreate.h
	${IRODS_SOURCE_DIR}/lib/api/include/subStructFileGet.h
	${IRODS_SOURCE_DIR}/lib/api/include/subStructFileLseek.h
	${IRODS_SOURCE_DIR}/lib/api/include/subStructFileMkdir.h
	${IRODS_SOURCE_DIR}/lib/api/include/subStructFileOpen.h
	${IRODS_SOURCE_DIR}/lib/api/include/subStructFileOpendir.h
	${IRODS_SOURCE_DIR}/lib/api/include/subStructFilePut.h
	${IRODS_SOURCE_DIR}/lib/api/include/subStructFileRead.h
	${IRODS_SOURCE_DIR}/lib/api/include/subStructFileReaddir.h
	${IRODS_SOURCE_DIR}/lib/api/include/subStructFileRename.h
	${IRODS_SOURCE_DIR}/lib/api/include/subStructFileRmdir.h
	${IRODS_SOURCE_DIR}/lib/api/include/subStructFileStat.h
	${IRODS_SOURCE_DIR}/lib/api/include/subStructFileTruncate.h
	${IRODS_SOURCE_DIR}/lib/api/include/subStructFileUnlink.h
	${IRODS_SOURCE_DIR}/lib/api/include/subStructFileWrite.h
	${IRODS_SOURCE_DIR}/lib/api/include/syncMountedColl.h
	${IRODS_SOURCE_DIR}/lib/api/include/ticketAdmin.h
	${IRODS_SOURCE_DIR}/lib/api/include/unbunAndRegPhyBunfile.h
	${IRODS_SOURCE_DIR}/lib/api/include/unregDataObj.h
	${IRODS_SOURCE_DIR}/lib/api/include/userAdmin.h
	${IRODS_SOURCE_DIR}/lib/api/include/zone_report.h
)

set(
	IRODS_LIB_RBUDP_INCLUDE_HEADERS
	${IRODS_SOURCE_DIR}/lib/rbudp/include/QUANTAnet_rbudpBase_c.h
	${IRODS_SOURCE_DIR}/lib/rbudp/include/QUANTAnet_rbudpReceiver_c.h
	${IRODS_SOURCE_DIR}/lib/rbudp/include/QUANTAnet_rbudpSender_c.h
)

set(
	IRODS_SERVER_API_INCLUDE_HEADERS
	${IRODS_SOURCE_DIR}/server/api/include/rsAuthCheck.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsAuthPluginRequest.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsAuthRequest.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsAuthResponse.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsAuthenticate.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsBulkDataObjPut.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsBulkDataObjReg.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsChkNVPathPerm.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsChkObjPermAndStat.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsClientHints.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsCloseCollection.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsCollCreate.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsCollRepl.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsDataCopy.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsDataGet.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsDataObjChksum.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsDataObjClose.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsDataObjCopy.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsDataObjCreate.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsDataObjCreateAndStat.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsDataObjGet.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsDataObjLock.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsDataObjLseek.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsDataObjOpen.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsDataObjOpenAndStat.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsDataObjPhymv.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsDataObjPut.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsDataObjRead.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsDataObjRename.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsDataObjRepl.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsDataObjRsync.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsDataObjTrim.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsDataObjTruncate.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsDataObjUnlink.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsDataObjWrite.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsDataPut.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsEndTransaction.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsExecCmd.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsExecMyRule.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsExecRuleExpression.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsFileChksum.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsFileChmod.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsFileClose.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsFileClosedir.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsFileCreate.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsFileGet.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsFileGetFsFreeSpace.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsFileLseek.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsFileMkdir.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsFileOpen.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsFileOpendir.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsFilePut.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsFileRead.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsFileReaddir.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsFileRename.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsFileRmdir.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsFileStageToCache.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsFileStat.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsFileSyncToArch.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsFileTruncate.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsFileUnlink.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsFileWrite.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsGenQuery.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsGeneralAdmin.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsGeneralRowInsert.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsGeneralRowPurge.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsGeneralUpdate.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsGetHierFromLeafId.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsGetHierarchyForResc.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsGetHostForGet.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsGetHostForPut.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsGetLimitedPassword.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsGetMiscSvrInfo.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsGetRemoteZoneResc.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsGetRescQuota.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsGetTempPassword.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsGetTempPasswordForOther.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsGetXmsgTicket.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsIESClientHints.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsL3FileGetSingleBuf.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsL3FilePutSingleBuf.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsModAVUMetadata.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsModAccessControl.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsModColl.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsModDataObjMeta.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsObjStat.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsOpenCollection.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsOprComplete.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsPamAuthRequest.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsPhyBundleColl.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsPhyPathReg.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsProcStat.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsQuerySpecColl.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsRcvXmsg.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsReadCollection.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsRegColl.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsRegDataObj.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsRegReplica.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsRmColl.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsRuleExecDel.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsRuleExecMod.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsRuleExecSubmit.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsSendXmsg.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsServerReport.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsSetRoundRobinContext.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsSimpleQuery.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsSpecificQuery.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsSslEnd.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsSslStart.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsStreamClose.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsStreamRead.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsStructFileBundle.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsStructFileExtAndReg.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsStructFileExtract.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsStructFileSync.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsSubStructFileClose.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsSubStructFileClosedir.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsSubStructFileCreate.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsSubStructFileGet.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsSubStructFileLseek.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsSubStructFileMkdir.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsSubStructFileOpen.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsSubStructFileOpendir.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsSubStructFilePut.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsSubStructFileRead.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsSubStructFileReaddir.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsSubStructFileRename.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsSubStructFileRmdir.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsSubStructFileStat.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsSubStructFileTruncate.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsSubStructFileUnlink.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsSubStructFileWrite.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsSyncMountedColl.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsTicketAdmin.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsUnbunAndRegPhyBunfile.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsUnregDataObj.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsUserAdmin.hpp
	${IRODS_SOURCE_DIR}/server/api/include/rsZoneReport.hpp
)

set(
	IRODS_SERVER_CORE_INCLUDE_HEADERS
	${IRODS_SOURCE_DIR}/server/core/include/collection.hpp
	${IRODS_SOURCE_DIR}/server/core/include/dataObjOpr.hpp
	${IRODS_SOURCE_DIR}/server/core/include/fileOpr.hpp
	${IRODS_SOURCE_DIR}/server/core/include/initServer.hpp
	${IRODS_SOURCE_DIR}/server/core/include/irodsReServer.hpp
	${IRODS_SOURCE_DIR}/server/core/include/irodsXmsgServer.hpp
	${IRODS_SOURCE_DIR}/server/core/include/irods_api_calling_functions.hpp
	${IRODS_SOURCE_DIR}/server/core/include/irods_collection_object.hpp
	${IRODS_SOURCE_DIR}/server/core/include/irods_data_object.hpp
	${IRODS_SOURCE_DIR}/server/core/include/irods_database_constants.hpp
	${IRODS_SOURCE_DIR}/server/core/include/irods_database_factory.hpp
	${IRODS_SOURCE_DIR}/server/core/include/irods_database_manager.hpp
	${IRODS_SOURCE_DIR}/server/core/include/irods_database_object.hpp
	${IRODS_SOURCE_DIR}/server/core/include/irods_database_plugin.hpp
	${IRODS_SOURCE_DIR}/server/core/include/irods_database_types.hpp
	${IRODS_SOURCE_DIR}/server/core/include/irods_dynamic_cast.hpp
	${IRODS_SOURCE_DIR}/server/core/include/irods_file_object.hpp
	${IRODS_SOURCE_DIR}/server/core/include/irods_generic_database_object.hpp
	${IRODS_SOURCE_DIR}/server/core/include/irods_get_l1desc.hpp
	${IRODS_SOURCE_DIR}/server/core/include/irods_mysql_object.hpp
	${IRODS_SOURCE_DIR}/server/core/include/irods_oracle_object.hpp
	${IRODS_SOURCE_DIR}/server/core/include/irods_physical_object.hpp
	${IRODS_SOURCE_DIR}/server/core/include/irods_postgres_object.hpp
	${IRODS_SOURCE_DIR}/server/core/include/irods_resource_backport.hpp
	${IRODS_SOURCE_DIR}/server/core/include/irods_resource_constants.hpp
	${IRODS_SOURCE_DIR}/server/core/include/irods_resource_manager.hpp
	${IRODS_SOURCE_DIR}/server/core/include/irods_resource_plugin.hpp
	${IRODS_SOURCE_DIR}/server/core/include/irods_resource_plugin_impostor.hpp
	${IRODS_SOURCE_DIR}/server/core/include/irods_resource_redirect.hpp
	${IRODS_SOURCE_DIR}/server/core/include/irods_resource_types.hpp
	${IRODS_SOURCE_DIR}/server/core/include/irods_server_api_call.hpp
	${IRODS_SOURCE_DIR}/server/core/include/irods_server_api_table.hpp
	${IRODS_SOURCE_DIR}/server/core/include/irods_server_control_plane.hpp
	${IRODS_SOURCE_DIR}/server/core/include/irods_server_state.hpp
	${IRODS_SOURCE_DIR}/server/core/include/irods_structured_object.hpp
	${IRODS_SOURCE_DIR}/server/core/include/miscServerFunct.hpp
	${IRODS_SOURCE_DIR}/server/core/include/objDesc.hpp
	${IRODS_SOURCE_DIR}/server/core/include/objMetaOpr.hpp
	${IRODS_SOURCE_DIR}/server/core/include/physPath.hpp
	${IRODS_SOURCE_DIR}/server/core/include/procLog.h
	${IRODS_SOURCE_DIR}/server/core/include/resource.hpp
	${IRODS_SOURCE_DIR}/server/core/include/rodsAgent.hpp
	${IRODS_SOURCE_DIR}/server/core/include/rodsConnect.h
	${IRODS_SOURCE_DIR}/server/core/include/rodsServer.hpp
	${IRODS_SOURCE_DIR}/server/core/include/rsApiHandler.hpp
	${IRODS_SOURCE_DIR}/server/core/include/rsGlobalExtern.hpp
	${IRODS_SOURCE_DIR}/server/core/include/rsIcatOpr.hpp
	${IRODS_SOURCE_DIR}/server/core/include/rsLog.hpp
	${IRODS_SOURCE_DIR}/server/core/include/specColl.hpp
	${IRODS_SOURCE_DIR}/server/core/include/xmsgLib.hpp
)

set(
	IRODS_SERVER_ICAT_INCLUDE_HEADERS
	${IRODS_SOURCE_DIR}/server/icat/include/icatDefines.h
	${IRODS_SOURCE_DIR}/server/icat/include/icatGlobalsExtern.hpp
	${IRODS_SOURCE_DIR}/server/icat/include/icatHighLevelRoutines.hpp
	${IRODS_SOURCE_DIR}/server/icat/include/icatStructs.hpp
)

set(
	IRODS_SERVER_RE_INCLUDE_HEADERS
	${IRODS_SOURCE_DIR}/server/re/include/irods_ms_plugin.hpp
	${IRODS_SOURCE_DIR}/server/re/include/irods_re_plugin.hpp
	${IRODS_SOURCE_DIR}/server/re/include/irods_re_namespaceshelper.hpp
	${IRODS_SOURCE_DIR}/server/re/include/irods_re_structs.hpp
	${IRODS_SOURCE_DIR}/server/re/include/irods_re_ruleexistshelper.hpp
	${IRODS_SOURCE_DIR}/server/re/include/irods_re_serialization.hpp
	${IRODS_SOURCE_DIR}/server/re/include/locks.hpp
	${IRODS_SOURCE_DIR}/server/re/include/msiHelper.hpp
	${IRODS_SOURCE_DIR}/server/re/include/reAction.hpp
	${IRODS_SOURCE_DIR}/server/re/include/reDataObjOpr.hpp
	${IRODS_SOURCE_DIR}/server/re/include/reDefines.h
	${IRODS_SOURCE_DIR}/server/re/include/reIn2p3SysRule.hpp
	${IRODS_SOURCE_DIR}/server/re/include/reNaraMetaData.hpp
	${IRODS_SOURCE_DIR}/server/re/include/reSysDataObjOpr.hpp
	${IRODS_SOURCE_DIR}/server/re/include/reconstants.hpp
)

set(
	IRODS_SERVER_DRIVERS_INCLUDE_HEADERS
	${IRODS_SOURCE_DIR}/server/drivers/include/fileDriver.hpp
)

install(
	FILES
	${IRODS_GENERATED_HEADERS}
	${IRODS_LIB_CORE_INCLUDE_HEADERS}
	${IRODS_LIB_HASHER_INCLUDE_HEADERS}
	${IRODS_LIB_API_INCLUDE_HEADERS}
	${IRODS_LIB_RBUDP_INLUDE_HEADERS}
	${IRODS_SERVER_API_INCLUDE_HEADERS}
	${IRODS_SERVER_CORE_INCLUDE_HEADERS}
	${IRODS_SERVER_ICAT_INCLUDE_HEADERS}
	${IRODS_SERVER_RE_INCLUDE_HEADERS}
	${IRODS_SERVER_DRIVERS_INCLUDE_HEADERS}
	DESTINATION ${IRODS_INCLUDE_DIR}
	COMPONENT irods-development
	# COMPONENT ${IRODS_PACKAGE_COMPONENT_DEVELOPMENT_NAME}
)

install(
	EXPORT
	IRODSTargets
	DESTINATION ${IRODS_CMAKE_DIR}
	COMPONENT irods-development
	# COMPONENT ${IRODS_PACKAGE_COMPONENT_DEVELOPMENT_NAME}
)

include( CMakePackageConfigHelpers )
configure_package_config_file(
	${CMAKE_SOURCE_DIR}/cmake_config/IRODSConfig.cmake.not_yet_installed.in
	${CMAKE_BINARY_DIR}/IRODSConfig.cmake.not_yet_installed # suffix prevents cmake's find_package() from using this copy of the file
	INSTALL_DESTINATION ${IRODS_CMAKE_DIR}
	PATH_VARS IRODS_INCLUDE_DIR
)

install(
	FILES
	${CMAKE_BINARY_DIR}/IRODSConfig.cmake.not_yet_installed
	DESTINATION ${IRODS_CMAKE_DIR}
	COMPONENT irods-development
	# COMPONENT ${IRODS_PACKAGE_COMPONENT_DEVELOPMENT_NAME}
	RENAME IRODSConfig.cmake
)

write_basic_package_version_file(
	${CMAKE_BINARY_DIR}/IRODSConfigVersion.cmake
	VERSION ${IRODS_VERSION}
	COMPATIBILITY ExactVersion
)

install(
	FILES
	${CMAKE_BINARY_DIR}/IRODSConfigVersion.cmake
	DESTINATION ${IRODS_CMAKE_DIR}
	COMPONENT irods-development
	# COMPONENT ${IRODS_PACKAGE_COMPONENT_DEVELOPMENT_NAME}
)
