#====================
#
#====================

include(GNUInstallDirs)

set( IRODS_HOME_DIR ${CMAKE_INSTALL_FULL_LOCALSTATEDIR}/lib/irods )
set( IRODS_HOME_DIRECTORY ${IRODS_HOME_DIR} )

if( CMAKE_INSTALL_FULL_SYSCONFDIR STREQUAL "/etc" )
	set( IRODS_CONFIG_DIR ${CMAKE_INSTALL_FULL_SYSCONFDIR}/irods )
else()
	set( IRODS_CONFIG_DIR ${CMAKE_INSTALL_FULL_SYSCONFDIR} )
endif()

set( IRODS_SBIN_DIR ${CMAKE_INSTALL_FULL_SBINDIR} )
set( IRODS_INCLUDE_DIR ${CMAKE_INSTALL_FULL_INCLUDEDIR}/irods )
set( IRODS_LIBRARY_DIR ${CMAKE_INSTALL_FULL_LIBDIR} )
set( IRODS_CMAKE_DIR ${IRODS_LIBRARY_DIR}/cmake/irods )
set( IRODS_PLUGINS_DIR ${IRODS_LIBRARY_DIR}/irods/plugins )
set( IRODS_PLUGINS_DIRECTORY ${IRODS_PLUGINS_DIR} )
set( IRODS_DOC_DIR ${CMAKE_INSTALL_FULL_DATAROOTDIR}/doc/irods-${IRODS_VERSION} )

if( VERBOSE )
	message( STATUS "IRODS_HOME_DIR: ${IRODS_HOME_DIR}" )
	message( STATUS "IRODS_HOME_DIRECTORY: ${IRODS_HOME_DIRECTORY}" )
	message( STATUS "IRODS_SBIN_DIR: ${IRODS_SBIN_DIR}" )
	message( STATUS "IRODS_CONFIG_DIR: ${IRODS_CONFIG_DIR}" )
	message( STATUS "IRODS_INCLUDE_DIR: ${IRODS_INCLUDE_DIR}" )
	message( STATUS "IRODS_LIBRARY_DIR: ${IRODS_LIBRARY_DIR}" )
	message( STATUS "IRODS_CMAKE_DIR: ${IRODS_CMAKE_DIR}" )
	message( STATUS "IRODS_PLUGINS_DIR: ${IRODS_PLUGINS_DIR}" )
	message( STATUS "IRODS_PLUGINS_DIRECTORY: ${IRODS_PLUGINS_DIRECTORY}" )
	message( STATUS "IRODS_DOC_DIR: ${IRODS_DOC_DIR}" )
endif()
